const enum EAnimationType {
	EXPLOSION_SMALL = 'EXPLOSION_SMALL',
	EXPLOSION_LARGE = 'EXPLOSION_LARGE',
	INVINCIBLE = 'INVINCIBLE',
	SPAWN = 'SPAWN',
	SCORE_100 = 'SCORE_100',
	SCORE_200 = 'SCORE_200',
	SCORE_300 = 'SCORE_300',
	SCORE_400 = 'SCORE_400',
	SCORE_500 = 'SCORE_500'
}

export default EAnimationType;